sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2.103
services:
- docker
build:
  context: .
  dockerfile: ReviewITAPI/Dockerfile
os:
- linux
script: 
- dotnet restore
- dotnet build