sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2.103
services:
- docker
build:
  context: .
  dockerfile: ReviewITAPI/Dockerfile
os:
- linux
before_install:
- echo ${HOME}
- docker build -f "ReviewITAPI/Dockerfile" -t reviewitapi --label "com.reviewitapi.created-by=travis" .
- docker run -d --name travis_container -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "ASPNETCORE_HTTPS_PORT=44362" -e "ASPNETCORE_ENVIRONMENT=Development" -e ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/../.aspnet/https/aspnetapp.pfx -p 51395:80 -p 44362:443 reviewitapi

script: 
- docker exec travis_container ls
- docker stop $(docker ps -aq)
- dotnet restore
- dotnet build
- dotnet test