sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2.103
services:
- docker
build:
  context: .
  dockerfile: ReviewITAPI/Dockerfile
os:
- linux
script: 
- docker build -f "ReviewITAPI/Dockerfile" -t reviewitapi --label "com.reviewitapi.created-by=travis" .
- docker run -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "ASPNETCORE_HTTPS_PORT=44362" -e "ASPNETCORE_ENVIRONMENT=Development" -e ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ -p 51395:80 -p 44362:443 reviewitapi
- dotnet restore
- dotnet build